apiVersion: kubeadm.k8s.io/v1beta1
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  file:
    kubeConfigPath: /etc/kubernetes/discovery.yaml
  timeout: 5m0s
  tlsBootstrapToken: 9rfe7l.mq9taae0wiu871vn
kind: JoinConfiguration
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: external