apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: "external"
---
apiServer:
  certSANs:
  - 10.198.184.202
apiVersion: kubeadm.k8s.io/v1beta2
controlPlaneEndpoint: "10.198.184.202:6443"
kind: ClusterConfiguration
useHyperKubeImage: false
kubernetesVersion: "v1.19.0"
networking:
  dnsDomain: "cluster.local"
  serviceSubnet: "10.198.184.0/23"
  podSubnet: "10.244.0.0/16"