kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc-common
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
parameters:
  storagepolicyname: "Space-Efficient"
  fstype: ext4
